# Generated by Django 5.0.3 on 2024-03-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
