# Generated by Django 5.0.3 on 2024-03-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='state',
            field=models.CharField(choices=[('C', 'Completed'), ('T', 'To Do')], default='T', max_length=1),
        ),
    ]
