# Generated by Django 5.0.3 on 2024-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
