# Generated by Django 4.2.3 on 2024-03-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_createdat_tasks_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='updatedAt',
            field=models.DateField(),
        ),
    ]
