# Generated by Django 4.2.3 on 2024-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_createdat_alter_tasks_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
